/* ============================================================
   VSM F1 League — standings-data.js
   AUTO-GENERATED by tools/update_results.py — do not hand-edit.
   Run the results updater to regenerate this file.
   ============================================================ */

const STANDINGS_S1 = {
  "drivers": [
    {
      "name": "Norris",
      "team": "McLaren",
      "teamSlug": "mclaren",
      "isPlayer": false,
      "pts": 25,
      "pos": 1,
      "gap": "—"
    },
    {
      "name": "Verstappen",
      "team": "Red Bull",
      "teamSlug": "redbull",
      "isPlayer": false,
      "pts": 18,
      "pos": 2,
      "gap": "-7"
    },
    {
      "name": "Téo",
      "team": "Red Bull",
      "teamSlug": "redbull",
      "isPlayer": true,
      "pts": 15,
      "pos": 3,
      "gap": "-10"
    },
    {
      "name": "Antonelli",
      "team": "Mercedes",
      "teamSlug": "mercedes",
      "isPlayer": false,
      "pts": 12,
      "pos": 4,
      "gap": "-13"
    },
    {
      "name": "Tom",
      "team": "McLaren",
      "teamSlug": "mclaren",
      "isPlayer": true,
      "pts": 10,
      "pos": 5,
      "gap": "-15"
    },
    {
      "name": "Albon",
      "team": "Williams",
      "teamSlug": "williams",
      "isPlayer": false,
      "pts": 8,
      "pos": 6,
      "gap": "-17"
    },
    {
      "name": "Hülkenberg",
      "team": "Audi",
      "teamSlug": "audi",
      "isPlayer": false,
      "pts": 6,
      "pos": 7,
      "gap": "-19"
    },
    {
      "name": "Gasly",
      "team": "Alpine",
      "teamSlug": "alpine",
      "isPlayer": false,
      "pts": 4,
      "pos": 8,
      "gap": "-21"
    },
    {
      "name": "Rehan",
      "team": "Mercedes",
      "teamSlug": "mercedes",
      "isPlayer": true,
      "pts": 2,
      "pos": 9,
      "gap": "-23"
    },
    {
      "name": "Lawson",
      "team": "Racing Bulls",
      "teamSlug": "racingbulls",
      "isPlayer": false,
      "pts": 1,
      "pos": 10,
      "gap": "-24"
    },
    {
      "name": "Alonso",
      "team": "Aston Martin",
      "teamSlug": "astonmartin",
      "isPlayer": false,
      "pts": 0,
      "pos": 11,
      "gap": "-25"
    },
    {
      "name": "Bearman",
      "team": "Haas",
      "teamSlug": "haas",
      "isPlayer": false,
      "pts": 0,
      "pos": 12,
      "gap": "-25"
    },
    {
      "name": "Bortoleto",
      "team": "Audi",
      "teamSlug": "audi",
      "isPlayer": false,
      "pts": 0,
      "pos": 13,
      "gap": "-25"
    },
    {
      "name": "Bottas",
      "team": "Cadillac",
      "teamSlug": "cadillac",
      "isPlayer": false,
      "pts": 0,
      "pos": 14,
      "gap": "-25"
    },
    {
      "name": "Colapinto",
      "team": "Alpine",
      "teamSlug": "alpine",
      "isPlayer": false,
      "pts": 0,
      "pos": 15,
      "gap": "-25"
    },
    {
      "name": "Deshy",
      "team": "Ferrari",
      "teamSlug": "ferrari",
      "isPlayer": true,
      "pts": 0,
      "pos": 16,
      "gap": "-25"
    },
    {
      "name": "Kai",
      "team": "Ferrari",
      "teamSlug": "ferrari",
      "isPlayer": true,
      "pts": 0,
      "pos": 17,
      "gap": "-25"
    },
    {
      "name": "Lindblad",
      "team": "Racing Bulls",
      "teamSlug": "racingbulls",
      "isPlayer": false,
      "pts": 0,
      "pos": 18,
      "gap": "-25"
    },
    {
      "name": "Ocon",
      "team": "Haas",
      "teamSlug": "haas",
      "isPlayer": false,
      "pts": 0,
      "pos": 19,
      "gap": "-25"
    },
    {
      "name": "Pérez",
      "team": "Cadillac",
      "teamSlug": "cadillac",
      "isPlayer": false,
      "pts": 0,
      "pos": 20,
      "gap": "-25"
    },
    {
      "name": "Sainz",
      "team": "Williams",
      "teamSlug": "williams",
      "isPlayer": false,
      "pts": 0,
      "pos": 21,
      "gap": "-25"
    },
    {
      "name": "Stroll",
      "team": "Aston Martin",
      "teamSlug": "astonmartin",
      "isPlayer": false,
      "pts": 0,
      "pos": 22,
      "gap": "-25"
    }
  ],
  "constructors": [
    {
      "team": "McLaren",
      "teamSlug": "mclaren",
      "pts": 35,
      "pos": 1,
      "gap": "—"
    },
    {
      "team": "Red Bull",
      "teamSlug": "redbull",
      "pts": 33,
      "pos": 2,
      "gap": "-2"
    },
    {
      "team": "Mercedes",
      "teamSlug": "mercedes",
      "pts": 14,
      "pos": 3,
      "gap": "-21"
    },
    {
      "team": "Williams",
      "teamSlug": "williams",
      "pts": 8,
      "pos": 4,
      "gap": "-27"
    },
    {
      "team": "Audi",
      "teamSlug": "audi",
      "pts": 6,
      "pos": 5,
      "gap": "-29"
    },
    {
      "team": "Alpine",
      "teamSlug": "alpine",
      "pts": 4,
      "pos": 6,
      "gap": "-31"
    },
    {
      "team": "Racing Bulls",
      "teamSlug": "racingbulls",
      "pts": 1,
      "pos": 7,
      "gap": "-34"
    },
    {
      "team": "Aston Martin",
      "teamSlug": "astonmartin",
      "pts": 0,
      "pos": 8,
      "gap": "-35"
    },
    {
      "team": "Cadillac",
      "teamSlug": "cadillac",
      "pts": 0,
      "pos": 9,
      "gap": "-35"
    },
    {
      "team": "Ferrari",
      "teamSlug": "ferrari",
      "pts": 0,
      "pos": 10,
      "gap": "-35"
    },
    {
      "team": "Haas",
      "teamSlug": "haas",
      "pts": 0,
      "pos": 11,
      "gap": "-35"
    }
  ]
};
